projeto_automatizador_cv/Controllers/CurriculosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using projeto_automatizador_cv.Models;

namespace projeto_automatizador_cv.Controllers
{
    [Authorize]    
    public class CurriculosController : Controller

    {
        private readonly AppDbContext _context;
        public CurriculosController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var dados = await _context.Curriculos.Include(c => c.Experiencias).ToListAsync();

            return View(dados);
        }

        //CREATE
        public IActionResult Create()
        {
            var novoItem = new Curriculo
            {
                Experiencias = new List<Experiencia> { new Experiencia() }
            };
            return View(novoItem);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Curriculo curriculo)
        {
            if (ModelState.IsValid)
            {
                _context.Curriculos.Add(curriculo);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(curriculo);
        }

        //EDIT
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null)
                return NotFound();

            var dados = await _context.Curriculos.Include(c => c.Experiencias).FirstOrDefaultAsync(c => c.Candidato == id);

            if (dados == null)
                return NotFound();

            return View(dados);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, Curriculo curriculo)
        {
            if (id != curriculo.Candidato)
                return NotFound();

            if (ModelState.IsValid)
            {
                _context.Entry(curriculo).Collection(c => c.Experiencias).EntityEntry.State = EntityState.Detached;

                var existingExperiencias = await _context.Experiencias
                    .Where(e => e.CurriculoCandidato == id)
                    .ToListAsync();

                foreach (var existingExperiencia in existingExperiencias)
                {
                    if (!curriculo.Experiencias.Any(e => e.Id == existingExperiencia.Id))
                        _context.Experiencias.Remove(existingExperiencia);
                }

                foreach (var experiencia in curriculo.Experiencias)
                {
                    experiencia.CurriculoCandidato = id;
                    if (experiencia.Id == 0)
                        _context.Experiencias.Add(experiencia);
                    else
                        _context.Experiencias.Update(experiencia);
                }

                _context.Curriculos.Update(curriculo);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View();
        }

        //DETAILS
        public async Task<IActionResult> Details(string? id)
{
            if (id == null)
                return NotFound();

            var dados = await _context.Curriculos
                .Include(c => c.Experiencias)
                .FirstOrDefaultAsync(c => c.Candidato == id);

            if (dados == null)
                return NotFound();

            return View(dados);
}

        //DELETE
        public async Task<IActionResult> Delete(string? id)
        {
            if (id == null)
                return NotFound();

            var dados = await _context.Curriculos.FindAsync(id);

            if (dados == null)
                return NotFound();

            return View(dados);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(string? id)
        {
            if (id == null)
                return NotFound();

            var dados = await _context.Curriculos.FindAsync(id);

            if (dados == null)
                return NotFound();

            _context.Curriculos.Remove(dados);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

    }
}

projeto_automatizador_cv/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Automatizador de Currículos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/projeto_automatizador_cv.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <div>
                        <img src="~/css/img/GFT_LogoFundo.jpg" class="logo" alt="Logo GFT">
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Curriculos" asp-action="Index">Currículos</a>
                            </li>

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuários</a>
                                </li>
                            }
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" style="color:#B02a87 !important" asp-area="" asp-controller="Usuarios" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" font-weight: bold" asp-area="" asp-controller="Usuarios" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>